guiceModuleClass: "com.flipkart.flux.examples.externalevents.SellerVerificationWorkflowModule"
workflowClasses: ["com.flipkart.flux.examples.decision.NotificationService",
                  "com.flipkart.flux.examples.decision.UserDataService",
                  "com.flipkart.flux.examples.decision.UserVerificationService",
                  "com.flipkart.flux.examples.decision.UserVerificationWorkflow",
                  "com.flipkart.flux.examples.concurrent.EmailDispatcher",
                  "com.flipkart.flux.examples.concurrent.EmailMarketingWorkflow",
                  "com.flipkart.flux.examples.externalevents.ManualSellerVerificationFlow",
                  "com.flipkart.flux.examples.externalevents.ManualSellerVerificationService",
                  "com.flipkart.flux.examples.externalevents.NotificationService",
                  "com.flipkart.flux.examples.externalevents.SellerDataService",
                  "com.flipkart.flux.examples.cancelpath.CancelPathWorkflow",
                  "com.flipkart.flux.examples.benchmark.ArithmeticOperations",
                  "com.flipkart.flux.examples.benchmark.BenchmarkWorkFlowA",
                  "com.flipkart.flux.examples.benchmark.ArithmeticOperationsExtended",
                  "com.flipkart.flux.examples.benchmark.BenchmarkWorkFlowAExtended",
                  "com.flipkart.flux.examples.benchmark.BenchmarkWorkflowLatentSimulation",
                  "com.flipkart.flux.examples.benchmark.LatentArithmeticOperations",
                  "com.flipkart.flux.examples.benchmark.PaymentGatewayTasks",
                  "com.flipkart.flux.examples.benchmark.PaymentGatewayWF",
                  "com.flipkart.flux.examples.eventupdate.EventUpdateWorkflow",
                  "com.flipkart.flux.examples.replayevents.validateStateWithMultipleReplayEvent.SampleReplayEventOnStateWithMultipleReplayEvent",
                  "com.flipkart.flux.examples.replayevents.validateSameReplayEventOnMoreThanOneState.SameReplayEventOnMoreThanOneState",
                  "com.flipkart.flux.examples.replayevents.ReplayEventWorkflow",
                  "com.flipkart.flux.examples.replayevents.ReplayEventWorkflow2"]